branches:
  only:     
    - master

environment:
  matrix:
    - configuration: Clang
      platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      fast_finish: true

    - configuration: MSVC
      platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      fast_finish: true

build_script:
  - ps: |
      .\build.ps1 -Compiler Clang

for:
  - matrix:
      only:
        - configuration: MSVC
    build_script:
      - ps: |
          .\build.ps1 -Compiler MSVC
    test_script:
      - cmd:
          .\tests\tests.exe

