#ifndef CLIENTSERVER_INCLUDE_DETAIL_PRECOMPILED_HPP
#define CLIENTSERVER_INCLUDE_DETAIL_PRECOMPILED_HPP

#ifdef _WIN32
#  define WIN32_LEAN_AND_MEAN
#endif

#include "ErrHandler.hpp"
#include "StringUtils.hpp"

#endif //CLIENTSERVER_INCLUDE_DETAIL_PRECOMPILED_HPP
